#include <stdio.h>
#include <conio.h>

void main()
{
	 int n, d;
	 clrscr();
	 textcolor(RED);
	 cprintf("\n\nIngrese un n£mero: ");
	 scanf("%d", &n);
	 d = n % 2;
	 if (d == 1)
	 {
		cprintf("\n\nEl n£mero es impar");
	 }
	 else
	 cprintf("\n\nEl n£mero es par");
	 printf("\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nPresione una tecla para salir");
	 getch();
}