#include <stdio.h>
#include <conio.h>

void main()
{
	float base, alt;
	clrscr();
	textcolor(RED);
	cprintf("\nIngrese la base del tri ngulo: ");
	scanf("%f", &base);
	cprintf("\nIngrese la altura: ");
	scanf("%f", &alt);
	cprintf("\n\nLa superficie del tri ngulo es: %f" , (base * alt) / 2);
	printf("\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nPresione una tecla para salir");
	getch();
}
