#include<stdio.h>
struct reg_alum
	   {
		char nombres[50];
		char apaterno[50];
		char amaterno[50];
		int edad;
		char sexo;
		float promedio;
	   };
void main()
		 {
		 struct reg_alum;
		 printf("nombre/s: ");gets(alumno.nombres);
		 printf("apeido paterno/s: ");gets(alumno.apaterno);
		 printf("apeido materno: ");gets(alumno.amaterno);
		 fflush(stdin):
		 printf("edad: ");scanf("%d"alumno.edad);
		 printf("sexo:");scanf("%c", alumno.sexo);
		  fflush(stdin):
		 printf("promedio: ");scanf("%f", alumno.promedio);
		 getch();
}